services:
  postgres:
    image: postgres:16-alpine
    container_name: alembic_practic_bd
    restart: unless-stopped 
    ports: 
      - "${POSTGRES_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-alembic_practic_bd}

    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: